// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package com.example.nettyclient;

public interface MsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.nettyclient.protobuf.Msg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string content = 2;</code>
   * @return The content.
   */
  String getContent();
  /**
   * <code>string content = 2;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
